apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # Runs on Fargate because namespace matches the profile
      containers:
        - name: my-app
          image: 441698169304.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: app-ns
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
